language: java
jdk:
  - oraclejdk8
before_install: 
  - chmod +x gradlew
  - ./gradlew clean cleanCache
install: ./gradlew setupCIWorkspace -S
script: ./gradlew build -S
notifications:
  email: false
env:
  global:
    TERM=dumb
