# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: travisj/build-number-action@v1.0.2
      id: production-line
    - name: Set up build number
      run: echo $BUILD_NUMBER
      env: 
        BUILD_NUMBER: ${{ steps.production-line.outputs.build-number }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup build environment
      run: ./gradlew setupCIWorkspace
    - name: Build
      run: ./gradlew build
    - name: Publish package
      run: ./gradlew jar
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with: 
        name: modpack
        path: ./build/libs/*
      
